### ISSUE TITLE
How to use lua-prepend-path?

### ISSUE THREAD

**Issue by shadow7412** [haproxytech/haproxy-lua-http#9]
I'd really appreciate an example on the page. Instead of just mentioning this in passing, could you give a quick example of the line that should be added to haproxy.conf?

And for those running an older version - what is the alternative?

**Comment by TimWolla** [comment]
> I'd really appreciate an example on the page. Instead of just mentioning this in passing, could you give a quick example of the line that should be added to haproxy.conf?

This is explained in the HAProxy documentation in detail: https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#3.1-lua-prepend-path

> And for those running an older version - what is the alternative?

Putting the library into the default Lua path or messing around with `package.path` within your script before `require`ing the library.
